# Generated by Django 6.1.1 on 2026-09-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=120, verbose_name='样本名称')),
                ('sample_type', models.CharField(max_length=80, verbose_name='样本类型')),
                ('project_type', models.CharField(choices=[('amplicon', '扩增子'), ('transcriptome', '转录组')], max_length=20, verbose_name='项目类型')),
                ('status', models.CharField(choices=[('shipped', '已寄送'), ('received', '已接收'), ('experiment_started', '开始实验'), ('completed', '已完成')], default='shipped', max_length=24, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx')],
            },
        ),
    ]
